import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {TYPES,validateActivities,filterActivities,pickActivity} from '../js/core.js';
const data=JSON.parse(await readFile(new URL('../activities.json',import.meta.url),'utf8'));
test('44 platných aktivít a oba stupne',()=>{validateActivities(data);assert.equal(data.length,44);for(const g of [1,2]) assert.equal(data.filter(a=>a.gradeLevel===g).length,22);});
test('Všetky typy a tempa vracajú iba zodpovedajúce aktivity pre oba stupne',()=>{for(const grade of [1,2]) for(const filter of [{kind:'all'},...TYPES.map(value=>({kind:'type',value})),...['pokojné','živé'].map(value=>({kind:'tempo',value}))]){const pool=filterActivities(data,grade,filter);assert.ok(pool.length);for(let i=0;i<30;i++){const a=pickActivity(pool);assert.equal(a.gradeLevel,grade);if(filter.kind==='type')assert.ok(a.types.includes(filter.value));if(filter.kind==='tempo')assert.equal(a.tempo,filter.value);}}});
test('Obľúbené rešpektujú stupeň a prázdny výber',()=>{const ids=[data[0].id,data[22].id];assert.deepEqual(filterActivities(data,1,{kind:'favorites'},ids),[data[0]]);assert.equal(pickActivity([]),null);assert.deepEqual(filterActivities(data,2,{kind:'favorites'},[]),[]);});
test('Ďalšia aktivita sa neopakuje, jedna možnosť funguje',()=>{const pool=data.slice(0,3);for(let i=0;i<30;i++)assert.notEqual(pickActivity(pool,pool[0].id).id,pool[0].id);assert.equal(pickActivity([pool[0]],pool[0].id),pool[0]);});
test('Nová aktivita je automaticky súčasťou výberu',()=>{const a={...data[0],id:'nova-aktivita'};assert.ok(filterActivities(validateActivities([...data,a]),1,{kind:'type',value:a.types[0]}).some(x=>x.id===a.id));});
test('Validátor odmieta duplicitné ID a neznáme kategórie',()=>{assert.throws(()=>validateActivities([...data,data[0]]));assert.throws(()=>validateActivities([{...data[0],types:['Neznámy typ']}]));});
